spring.application.name=food-delivery-api

server.port=8080
spring.docker.compose.enabled=true

spring.docker.compose.file=compose.yaml
spring.datasource.username=root
spring.datasource.password=verysecret
spring.datasource.url=jdbc:mysql://localhost/food-delivery-api-db?createDatabaseIfNotExist=true&serverTimezone=UTC
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
#spring.jpa.hibernate.ddl-auto=validate

spring.flyway.locations=classpath:db/migration,classpath:db/dev_import
spring.flyway.clean-on-validation-error=true

#spring.datasource.hikari.maximum-pool-size=5
#spring.datasource.hikari.minimum-idle=3
#spring.datasource.hikari.idle-timeout=10000

spring.jackson.deserialization.fail-on-unknown-properties=true
spring.jackson.deserialization.fail-on-ignored-properties=true

logging.level.root=INFO
logging.level.com.fasterxml.jackson=DEBUG
logging.level.com.fasterxml.jackson.databind=DEBUG
logging.level.com.fasterxml.jackson.core=DEBUG

logging.level.org.springframework.http.converter.json=TRACE
logging.level.org.springframework.web.servlet.mvc.method.annotation=TRACE
spring.mvc.log-request-details=true